#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
RUN="${1:-shvbroker}"
ARGS=( "$@" )
shift
echo "command: ${RUN}"
echo "args:" "${ARGS[@]}"
"${SCRIPT_DIR}/usr/bin/${RUN}" "${ARGS[@]}"
